### ISSUE TITLE
Recuperar Usuario/s

### ISSUE THREAD

**Issue by sesnaola** [sesnaola/RedSocial#23]
Método GET para recuperar un usuario si se especifica ID y recuperarlos todos si no se especifica.

**Comment by persa26** [comment]
When retrieving concrete user remove the 'users' tag

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/42568197/172125965-766144d5-a651-420e-9e82-a93aeef9bb42.png">

**Comment by persa26** [comment]
We also need an endpoint where we can retrieve the user with email/password for the login page.
